### ISSUE TITLE
Load Errors when using detect_serial_baudrate.rb:3

### ISSUE THREAD

**Issue by claudijd** [claudijd/serial-tools#4]
Exact details here:

https://twitter.com/NatlSecNick/status/297933560847929344
https://twitter.com/NatlSecNick/status/297934381476106240

Initial Response:

https://twitter.com/claudijd/status/298104140394008577

**Comment by claudijd** [comment]
Try these steps and please paste in your results and I'll gladly help you resolve:

claudijd@macbookpro [~] $ ruby -v
ruby 1.9.1p243 (2009-07-16 revision 24175) [i386-darwin10.8.0]
claudijd@macbookpro [~] $ gem list | grep serialport
serialport (1.1.0)
claudijd@macbookpro [~] $ irb

> > require 'serialport'
> > => true

**Comment by natlsecnick** [comment]
![RubyTXRX](https://f.cloud.github.com/assets/3464833/122066/8e3d3092-6e29-11e2-8c04-7ac51381ea82.PNG)
Thanks for the help. 

For ruby -v: 
root@bt:~# ruby -v
ruby 1.9.2dev (2010-07-02) [i486-linux]

For gem list | grep serialport: 
root@bt:~# gem list | grep serialport
serialport (1.1.0)

For irb, require 'serialport':
root@bt:~# irb
irb(main):001:0> require 'serialport'
LoadError: no such file to load -- serialport
    from (irb):1:in `require'
    from (irb):1
    from /usr/bin/irb:12:in`<main>'
irb(main):002:0>

**Comment by natlsecnick** [comment]
For more details on the exact setup I'm running: 
I'm utilizing the 3DR Radio Telemetry Kit to a provide a transparent wireless UART connection. (See http://eclipsesource.com/blogs/2012/10/17/serial-communication-in-java-with-raspberry-pi-and-rxtx/)

And this is what the serial tools procedure looks like so far.

![walkthrough](https://f.cloud.github.com/assets/3464833/122181/ef298f54-6e38-11e2-8ca6-94e69de03288.PNG)

**Comment by claudijd** [comment]
I believe this is related to the rubygems version on BT R3.

I initially thought the issue was needing to require rubygems like so:

require 'rubygems'

But in trying it on BTR3, I had no luck.  I checked the rubygems version that's there by default and it's...

gem --version
1.3.7

When I run this on my machine, I get the following:

claudijd@macbookpro [~] $ gem --version
1.8.10

I tried upgrading the rubygems version in BTR3, but debian controls their rubygems packages a bit more tightly and only allows you to us their version installed via apt-get.  According to the upstream repo it's tied to, 1.3.7 is the latest.

I'm still investigating further, but figured I'd toss you this update as to where I am with it.

**Comment by natlsecnick** [comment]
Hm. I'm using VMs, I could just install another linux OS. Anything you would recommend that works best?

**Comment by claudijd** [comment]
I personally prefer RVM (ruby version manager - https://rvm.io/), which allows you to have more than one ruby version installed and swap between them.  I'm actually going to install it on BTR3 now just to make sure it will work before giving you instructions.

Note: if this works, it will not require a separate VM.

**Comment by natlsecnick** [comment]
That'd be great. I appreciate the help, I'm not acquainted to ruby whatsoever.

**Comment by claudijd** [comment]
#Install RVM and the latest Ruby version

curl -L https://get.rvm.io | bash -s stable --ruby

#Source in the rvm binary

source /usr/local/rvm/scripts/rvm

#Show what ruby versions you have installed under RVM

rvm list

#Select a Ruby Version to use

rvm use 1.9.3-p374

#Install SerialPort gem under this ruby version

gem install serialport

#Use IRB to verify that you're all good with the serial port require

irb
require 'serialport'

#To go back to the system ruby

rvm use system

#To go back to this environment

rvm use 1.9.3-p374

And that sir, is the magic of RVM.  It should work flawlessly on BTR3, let me know either way :)

**Comment by claudijd** [comment]
I'm going to leave this issue open until I find some time to investigate what the heck is going on with the BTR3 gem stuff, but in the meantime, the above should get you hacking with serial-tools :)

**Comment by natlsecnick** [comment]
Ah! MUCH APPRECIATED! The script is indeed running. Quick Q on the next section. 

As it is cycling through the various baudrates, I'm hitting enter to see if I get prompt back.

Every time it rolls into the next range, I hit enter, but never get prompt up. Any suggestions on this troubleshoot section? The radio units I am utilizing show they are connected. Do I need to configure anything on the raspberry pi side?

**Comment by natlsecnick** [comment]
Actually, I get one weird response. Not exactly what we were looking for, but the only response so far...
![baudrate](https://f.cloud.github.com/assets/3464833/122254/4fd519e2-6e41-11e2-89cd-a1c3e0fed871.PNG)

**Comment by claudijd** [comment]
Some things to consider when troubleshooting:

1.) The Pi is 3.3v (are you sure your controller is 3.3v and not 5.5v?)

I wrote a blog post, which includes a narrative and a video describing the process end-to-end of using the tools.
http://blog.spiderlabs.com/2012/12/getting-terminal-access-to-a-cisco-linksys-e-1000.html

2.) You might consider whether your Rx (Receive) and Tx (Transmit) wires are not properly crossed.  You can try again by switching only one side of the connection wires and repeating the steps.

3.) If you're trying to do the whole wireless thing that's described in that article you referenced, I would recommend connecting directly to the Pi first to make sure you can confirm it's working properly.  Once that is done, you can add the wireless stuff and troubleshoot that via the manufacturer instructions.

Note: I do nothing with Hardware flow control in serial-tools right now.  If that's something that is required, you might consider trying a more traditional terminal emulator and using the baud settings from vendor.  If that all works fine, but you'd like to do it with serial-tools let me know and I can probably add it to the baud bruteforcing sequence. 

Also, the Pi is 115200-8-N-1 and 3.3v.  I have confirmed this in the readme of this project.

**Comment by claudijd** [comment]
Also, I tried a couple other times with BackTrack and it looks like it's known to (1) have gem path issues in general and (2) have general bugginess with 1.9.2.  As such, I'm going to chalk this up as a problem with BT and not the serial-tools.

There is more discussion on this in the BackTrack forums, but I can't say I'm trilled with the suggested fixes and their potential impact on other ruby tools in BT:

http://www.backtrack-linux.org/forums/showthread.php?t=40446 ("Problems with ruby1.9.2")

My suggestion would be to stick with RVM solution until BT updates their system ruby.  If you're looking to install somewhere else (like a personal computer running Linux/OSX), I would suggest just install the latest version of Ruby, Rubygems and gem install the serialport gem.

Good Luck!
